---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  aws-node
---
apiVersion: v1
kind: Namespace
metadata:
  name:  kube-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: karpenter-pre-req-eksctl-job
spec:
  template:
    metadata:
      labels:
        app: karpenter-setup-eksctl-job
    spec:
      serviceAccountName: aws-node
      containers:
      - name: karpenter-setup-eksctl-job
        image: chatwork/eksctl:latest
        env:
          - name: CLUSTER_NAME
            value: "karp-duke"
          - name: ACCOUNT_ID
            value: "844333597536"
        command:
          - /bin/sh
          - -c
          - |
            yum install git -y > /dev/null 2>&1
            git clone https://github.com/anuddeeph1/pre-requisite-karpenter.git
            cd pre-requisite-karpenter/karpenter-pre-req
            chmod +x eksctl-updatecm-sa.sh
            ./eksctl-updatecm-sa.sh $CLUSTER_NAME $ACCOUNT_ID
      restartPolicy: Never
